- pyworkflow/em/protocol/protocol_align_movies.py
- pyworkflow/em/protocol/protocol_micrographs.py
Here I'm applying a patch from scipion PR: https://github.com/I2PC/scipion/pull/2048
> Apply scipion pr2048

- pyworkflow/gui/form.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/project/project.py
- pyworkflow/protocol/protocol.py
Fix discovering outputs in SubclassesTreeProvider
Do not show "Analyze result" if nothing selected.
> iterOutputNew: tolerate missing outputs if present in the array but absent as attribute.

- pyworkflow/__init__.py
- pyworkflow/gui/project/project.py
- pyworkflow/utils/path.py
Issues involved:
https://github.com/I2PC/scipion/issues/2067
https://github.com/I2PC/scipion/issues/1875
> Jj fix issues

- pyworkflow/apps/pw_schedule_run.py
When a protocol remains scheduled, it's worth to inspect the `Runs/xxxxx_protClassName/logs/schedule.log`. However, it doesn't describe too much that reason.
With this PR, `the schedule.log` is updated with a string for each reason to keep scheduled.
> Updating schedule.log in such a way to make it more descriptive

- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/utils/process.py
It looks already fixed in pwem, but not here
> fix psutil, typo in debugOn

- pyworkflow/__init__.py
- pyworkflow/plugin.py
Removed EM_ROOT and _defineEmVar, this was moved to scipion-em.
Should be merged together with:
https://github.com/scipion-em/scipion-em/pull/33
> Remove EM_ROOT

- pyworkflow/__init__.py
- pyworkflow/constants.py
- pyworkflow/gui/matplotlib_image.py
- pyworkflow/gui/project/viewdata.py
- pyworkflow/gui/project/viewprojects.py
- pyworkflow/gui/widgets.py
- pyworkflow/protocol/hosts.py
- pyworkflow/protocol/launch.py
- pyworkflow/tests/test_utils.py
Wizards update. Created constants file and updated references in pyworkflow plugin.
> Jj update wiz add constants

- pyworkflow/gui/project/project.py
- pyworkflow/object.py
Removing hardcoded methods to create subsets(Allowing to create subsets of Tomograms and Subtomograms)
> * Removing hardcoded methods to create subsets

- pyworkflow/__init__.py
- pyworkflow/config.py
- pyworkflow/constants.py
- pyworkflow/plugin.py
- pyworkflow/utils/utils.py
Fix expansion of environment variables in config...and more config reorganization.
> Config expand

- pyworkflow/tests/tests.py
Expand AssertSize so it  checks if a Set is of a determined size with a percentage (base 1) of difference
> Expand AssertSize

- pyworkflow/apps/pw_protocol_run.py
- pyworkflow/protocol/hosts.py
This restores old behaviour for host.conf files
> Devel fixes

- pyworkflow/protocol/protocol.py
Using json.dumps(data, default=lambda x: None) to just suppress Type Errors and dump anything in data which cannot be serialized as null
> * Using json.dumps(data, default=lambda x: None)

- pyworkflow/gui/project/project.py
Closes https://github.com/scipion-em/scipion-em/issues/114
> do not show General /User configuration menu if missing.

- pyworkflow/constants.py
- pyworkflow/gui/form.py
- pyworkflow/plugin.py
- pyworkflow/protocol/protocol.py
- setup.py
Minor tweaks and fixes:
Fixes: https://github.com/scipion-em/scipion-pyworkflow/issues/102
Hides some debug lines in the log
Prints the plugin __version__ in the log
Robust to validateInstallation exceptions
> Validate installation

- pyworkflow/gui/form.py
Closes #115 --> https://github.com/scipion-em/scipion-pyworkflow/issues/115
> debug print lines removed

- pyworkflow/protocol/protocol.py
So far mandatory ones are author, year.
> allow citations without doi or journal/booktitle.

- pyworkflow/project/scripts/schedule.py
- pyworkflow/tests/tests.py
- pyworkflow/utils/utils.py
Highlight where protocol log lines are and flush.
Use enum for StrColors and missing colorStr functions added
> use new blueStr.

- pyworkflow/constants.py
- pyworkflow/plugin.py
> path of CONDA_ACTIVATION_CMD is not replaced by SCIPION_HOME anymore.

- pyworkflow/utils/mpi.py
Fixing the MPI encoding error 
Closes #137
> * Fixing the MPI encoding error

- pyworkflow/gui/project/viewprotocols.py
show bibtex even if some reference id are not defined in the bibtex file.
version bumped.
> bibtext export fix

- pyworkflow/constants.py
- pyworkflow/project/project.py
- pyworkflow/protocol/protocol.py
* Fixing an error importing/exporting workflow.json with the prerequisites parameter
* Version bumped
* Closes #151
> * Fixing an error importing/exporting workflow.json with the prerequisites parameter

- pyworkflow/constants.py
- pyworkflow/gui/project/base.py
> Fix online help url

- pyworkflow/gui/form.py
- pyworkflow/gui/widgets.py
- pyworkflow/utils/properties.py
Fix: Form, under a certain combination of Widgets hide and show + window resize ended up not growing and therefore not showing bottom widgets.py
Remove subtle black border in bottom left of the form
> Fix form window glitch

- pyworkflow/gui/project/viewprojects.py
- pyworkflow/project/manager.py
Delete project: avoid reloading projects, direct remove of the widget.
Project list 1005 based on ProjectInfo, avoiding project load.
ProjectInfo: creationtime and full path added as properties
> Speed up project list load

- pyworkflow/config.py
- pyworkflow/gui/project/viewprotocols.py
Defining an environment variable in order to refresh the displayed runs with a thread
> Refresh runs threads

- pyworkflow/utils/utils.py
Closes https://github.com/scipion-em/scipion-pyworkflow/issues/224
> rescue getToc

- pyworkflow/constants.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/text.py
- pyworkflow/project/project.py
- pyworkflow/project/scripts/fix_links.py
- pyworkflow/utils/path.py
- setup.py
This tolerates errors when loading a log with wrong non valid encoding, replacing them with a ?
> Fix nonutf in log

- pyworkflow/object.py
> Fix a cyclic import

- pyworkflow/gui/project/viewprotocols.py
Fix an error when expanding and collapsing a workflow node
> * Fix an error when expanding and collapsing a workflow node

- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/tree.py
Tolerate tree providers without getObjId() method
> collapse or not tree sections based on protocols.conf

- pyworkflow/gui/form.py
- pyworkflow/gui/project/base.py
- pyworkflow/utils/properties.py
> Show pyworkflow version too in the project window

- CHANGES.txt
- pyworkflow/constants.py
- pyworkflow/gui/browser.py
- pyworkflow/protocol/hosts.py
Allow multiple filehandlers for the same extension
CHANGES.txt updated
version bumped to 3.0.15
> do not suggest to delete hosts config if parsing fails

- pyworkflow/gui/dialog.py
- pyworkflow/gui/project/labels.py
- pyworkflow/gui/project/viewprotocols.py
- requirements.txt
it requires a scipion3 run pip install tkcolorpicker for developers.
> Uses a colorpicker better, in my opinion than the ubuntu/system one.

- pyworkflow/utils/utils.py
- requirements.txt
Timer class improvement when used in with clause.
Closes #253
> some dependencies updated (Not key ones like numpy or matplotlib)

- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/project/project.py
- Fixing an error resetting nodes with manual subset  
- Closes #288
> * Fixing an error resetting nodes with manual subset

- CHANGES.txt
- pyworkflow/constants.py
- pyworkflow/protocol/protocol.py
Close all sets when stoping a protocol 
- Closes #291
> * Close all sets when stoping a protocol

- pyworkflow/protocol/protocol.py
Fix a bug related with a missing 1 required positional argument in the setFailed method
> * Fix a bug related with a missing 1 required positional argument

- CHANGES.txt
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/project/project.py
- pyworkflow/protocol/protocol.py
* Fixing an error reporting the protocol wall time  
Closes #286
> * Fixing an error reporting the protocol wall time

- pyworkflow/gui/form.py
Finished protocol can't be modified  
- Closes #292
> * Finished protocol can't be modified

- .gitignore
- CHANGES.txt
- pyworkflow/gui/form.py
- pyworkflow/protocol/protocol.py
This will allow the connection of protocols in the GUI, even when the protocols have no output.
For this, each protocol may define de _possibleOutputs class attribute as an enum (see protocol class definition).
> Possible ouputs

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/gui/project/viewprotocols.py
Added a variable that is used in the view protocols in order to load first  the plugins that contains the main protocols.conf sections
> Priority package list

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/protocol/protocol.py
- pyworkflow/utils/reflection.py
Defining the variable SCIPION_STEPS_CHECK_SEC in order to control the time in which the execution is checked between the steps of a protocol
> * Defining the variable SCIPION_STEPS_CHECK_SEC

- pyworkflowtests/objects.py
- pyworkflowtests/protocols.py
- pyworkflowtests/tests/test_project.py
- pyworkflowtests/tests/test_protocol_execution.py
- pyworkflowtests/tests/test_protocol_output.py
> pyworkflowtests fixed

- CHANGES.txt
- pyworkflow/object.py
- pyworkflow/project/project.py
- pyworkflow/protocol/protocol.py
This fixes when scheduling a protocol with Scalars with pointers.
> Fix scalar with pointers

- pyworkflow/project/project.py
Fixes importing a partial workflow
> Fixes importing a workflow with Scalars with pointers.

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/constants.py
- pyworkflow/protocol/protocol.py
- pyworkflow/utils/log.py
* Creating in the config new constants to check the outputs
> * Defining a new format to handler the log

- CHANGES.txt
- pyworkflow/protocol/params.py
- pyworkflow/protocol/protocol.py
Allow passing just an id in insertStep
> Some methods commented

- CHANGES.txt
- pyworkflow/constants.py
- pyworkflow/gui/form.py
- pyworkflow/protocol/protocol.py
* Fixing a persistent error related with the logic of the EXECUTE/SCHEDULE button
> * Fixing a persistent error related with the logic of the EXECUTE/SCHEDULE button

- pyworkflow/config.py
- pyworkflow/protocol/protocol.py
Provide feedback when protocol definition fails about the exact parameter that is failing
Description added under Config variable to check if it shows up in the API
> Param definition feedback

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/constants.py
- pyworkflow/gui/browser.py
- pyworkflow/gui/dialog.py
- pyworkflow/gui/graph_layout.py
- pyworkflow/gui/gui.py
- pyworkflow/gui/project/base.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/tree.py
- pyworkflow/protocol/launch.py
- pyworkflow/protocol/protocol.py
- pyworkflow/utils/process.py
- Improvements in responsiveness to font size: Tables and automatic layouts. Object browser, Search windows.
- Filebrowser has 2 new shortcuts: "recent" and "Protocol folder"
Developers:
- Some modules switched to use logger instead of print: viewprotocols.py, browser.py and launch.py.
> Font responsiveness

- CHANGES.txt
- pyworkflow/apps/pw_schedule_run.py
- pyworkflow/gui/browser.py
- pyworkflow/gui/canvas.py
- pyworkflow/gui/project/viewprojects.py
- pyworkflow/gui/text.py
- pyworkflow/project/project.py
- pyworkflow/protocol/protocol.py
- pyworkflow/utils/log.py
- pyworkflow/utils/utils.py
This fixes the file browser and the colors in the terminal.
Additionally brings standard logging to some modules
> Fix browser

- CHANGES.txt
- pyworkflow/constants.py
- pyworkflow/gui/text.py
- pyworkflow/utils/path.py
- pyworkflow/utils/process.py
- pyworkflow/utils/utils.py
- Commands in the log are "announced" by "** Running command: **"
>   - Green lines in log are lighter, colored lines are back in the log.

- CHANGES.txt
- pyworkflow/gui/project/viewprojects.py
- Project list window: Auto refresh on window activate when data is older than 60 seconds
>   - Project list window: F5 on the filter box will refresh the list.

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/protocol/launch.py
- pyworkflow/protocol/protocol.py
- Protocol._cleanExtraFiles(): optional method to clean files other than tmp folder.
- Config.isScipionRunning(): To distinguish from just importing or running.
>  - Error in host.conf for clusters better described.

- CHANGES.txt
- pyworkflow/gui/gui.py
- pyworkflow/object.py
- pyworkflow/tests/tests.py
- pyworkflowtests/objects.py
- pyworkflowtests/tests/test_object.py
- TaseCase: compareSetProperties() added to compare 2 set's properties.
> Set implements copy() leaving mapper_path out.

- .github/workflows/build.yml
New github action to be executed on every push to devel branch
> Test conda-based core installation with different python

- CHANGES.txt
- pyworkflow/gui/form.py
- pyworkflow/gui/project/searchprotocol.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/project/viewprotocols_extra.py
- pyworkflow/project/project.py
- pyworkflow/protocol/protocol.py
- pyworkflow/utils/properties.py
> Refactoring Restart & Continue workflow option. Allowing to continue and restart a workflow from a protocol

- pyworkflow/gui/form.py
I did not remove localhost properly the first time :)
> fix layout

- pyworkflow/gui/plotter.py
- pyworkflow/gui/project/viewprotocols.py
These changes are necessary for scipion em PR https://github.com/scipion-em/scipion-em/pull/452
> minor tweaks

- pyworkflow/config.py
- pyworkflow/constants.py
- pyworkflow/gui/form.py
- pyworkflow/gui/project/viewprotocols.py
* Introducing a constants to define the default protocol execution mode.
* Catching the error if restartWorkflow or continueWorkflow method fails
> Introducing a constants to define the default protocol execution mode.

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/mapper/mapper.py
- pyworkflow/mapper/sqlite.py
- pyworkflow/object.py
- pyworkflow/utils/utils.py
- pyworkflowtests/tests/test_mappers.py
- pyworkflowtests/tests/test_object.py
Accepts strings or lists in operations, labels or groupby args.
Accepts id or _objId ar fields
- String.getListFromValues: works now with strings with an x inside (e.g.: _x _y)
- New utils method: valueToList (converts the argument into a list if is not a list): Useful for "dual type arguments) that can be a list or not
>  - Set.aggregate more flexible and versatile.

- CHANGES.txt
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/text.py
- pyworkflow/gui/tree.py
- pyworkflow/plugin.py
- pyworkflow/protocol/protocol.py
- pyworkflow/template.py
- pyworkflow/webservices/workflowhub.py
lists templates from workflow hub site
> Templates from wh

- CHANGES.txt
- pyworkflow/config.py
- pyworkflow/constants.py
- pyworkflow/gui/canvas.py
- pyworkflow/gui/form.py
- pyworkflow/gui/graph.py
- pyworkflow/gui/graph_layout.py
- pyworkflow/gui/project/project.py
- pyworkflow/gui/project/steps.py
- pyworkflow/gui/project/viewdata.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/widgets.py
- pyworkflow/object.py
- pyworkflow/plugin.py
- pyworkflow/project/config.py
- pyworkflow/project/manager.py
- pyworkflow/project/project.py
- pyworkflow/project/scripts/create.py
- pyworkflow/project/scripts/schedule.py
- pyworkflow/protocol/constants.py
- pyworkflow/protocol/executor.py
- pyworkflow/protocol/params.py
- pyworkflow/protocol/protocol.py
- pyworkflow/template.py
- pyworkflow/utils/graph.py
- pyworkflow/utils/properties.py
- pyworkflowtests/protocols.py
- pyworkflowtests/tests/test_protocol_execution.py
- Step details show it step needs a GPU
- Folder size not showing in protocol's tooltip: poor performance in some setups
- Threads field and help improved: Distinguish between "Scipion threads" and "Threads" (program threads)
- create script accepts a comment (location optional as -)
- GPU "queue":
Basic GPU queue implemented for a more robust GPU specification in combination with threads. See docs/user/threads-mpi-gpus.html help page in the doc when built. Linked in the help.
Tests added
> GPU queue (naive) but better that what we have. Docs comming.

- CHANGES.txt
- pyworkflow/gui/browser.py
- pyworkflow/gui/project/project.py
- pyworkflow/gui/project/viewprotocols.py
- pyworkflow/gui/widgets.py
- requirements.txt
- File browser: 2 new actions on right click: "delete" and "copy"
> Menu > Project > "Remove temporary files" remove folders too.
