scipion-em/scipion-pyworkflow

pyworkflow/protocol/protocol.py
renamed in Python 3 to urllib.request, urllib.parse and urllib.error.
Exception e isn't necessary because the last exception is automatically
captured inside pwutils.formatExceptionInfo()
=> Migration issue solved: the urllib module has been split into parts and

pyworkflow/protocol/protocol.py
overload getClassDomain because legacy protocols do not have a package associated to it and preclude the ppening of scipion
=> Legacy protocols

pyworkflow/object.py
Issue found in
scipion-em-xmipp/xmipp3/protocols/protocol_extract_particles_pairs.py
(_setupBasicProperties)
TypeError: unhashable type: 'Micrograph'
Solution: Hashability makes an object usable as a dictionary key and a
set member
=> __hash__ method added to object

pyworkflow/plugin.py
In this way one can save effort when importing some classes from a plugin like
```
prot1, prot2, ... = Domain.importFromPlugin('plugin1.protocols', ['prot1', 'prot2', ...])
```
or whatever.
The single option is also valid
```
prot3 = Domain.importFromPlugin('plugin1.protocols', 'prot3')
```
=> Allowing import several classes from the same plugin.module

pyworkflow/project/scripts/schedule.py
When scheduling a project, it could be useful to skip some of the protocols in order to wait until the user gets ready to manually launch it.
For example, in a streaming workflow where some parameter remains unknown at the beginning but after the first steps of the processing it becomes known. Then, the protocol that needs this parameter can be updated and launched without any disruption, letting continue with the rest of the workflow.
=> Allowing to ignore some protocols when scheduling

pyworkflow/gui/project/viewprotocols.py, pyworkflow/protocol/protocol.py
There is a bug that is causing that protocols "continue" mode does not work.
It is caused because picking dumps/loads bytes instead of str. So, there were two issues:
* Step arguments always evaluated different and continue did not found the proper step where to start
* In case that steps stores some "resultFiles" it was raising an error due to the encode('utf-8') call
Solution:
* Using json instead of pickle to store/retrieve with String
=> Fix continue for protocol Steps

pyworkflow/gui/gui.py
If a window which isn't the main Scipion window is generated from another main window, e. g. with Scipion template after the refactoring of the kickoff, in which a dialog is launched and then a form, being it called from the command line, so there's no Scipion main window. In that case, a tk.Tk() exists because if a tk.TopLevel(), as the dialog, is directly launched, it automatically generates a main tk.Tk(). Thus, after that first auto-tk.Tk(), another tk.Tk() was created here, and so the previous information was lost. Solution proposed is to generate the root as an invisible window if it doesn't exist previously, and make he first window generated a tk.Toplevel. After that, all steps executed later will go through the else statement, being that way each new tk.Toplevel() correctly …
=> Jj gui calling update

pyworkflow/apps/pw_run_tests.py, pyworkflowtests/tests/test_mappers.py
Before this PR, `--mode` and `--run` flags for test mode were incompatible (no test run) due to a couple of bugs that are fixed here.
Now, 
`scipion3 test --grep any-pattern-like-plugin-name --mode modules --run`
or
`scipion3 test --grep any-pattern-like-plugin-name --mode onlyclasses --run`
can be used. This is useful because without that modes every test is run twice (one for module one for class).
=> Bug fixing in running test plus grep

requirements.txt
Matplotlib 3.3 has a bug and needs to be downgraded to 3.2.2 that works.
To avoid the same possible issues with new versions I'm fixing the versions here.
=> fix versions.

pyworkflow/apps/pw_sync_data.py
In no verbose mode it will now output this:
````
scipion3 testdata --download groel
Scipion v3.0 () devel
Selected datasets: groel
Local copy of dataset groel detected.
Checking for updates...
Regenerating local MANIFEST...
Verifying MD5s...
Differences detected. Downloading data. Use -v for more details
````
I'm keeping the verbose mode.
Closes #119
=> Warn about files being downloaded when updating a dataset.

pyworkflow/gui/form.py, pyworkflow/template.py, requirements.txt
This PR:
Closes #128 (avoid .json in project names)
Relaxes requirements.txt to allow python3.5 installations (matplotlib and configparser were not compatible)
Close #123 : Removes e.message use.
=> aovid projects with .json in the name, requirements relaxed

pyworkflow/gui/form.py, pyworkflow/protocol/protocol.py, pyworkflow/utils/properties.py
Allow editing/saving/cloning queue parameters  
Closes #147
=> * Allow editing/saving/cloning queue parameters

pyworkflow/gui/text.py
For scipion-ed it is sometimes useful to open html output files from the "browse" option in the GUI. Treating html files the same way as any url fixes this.
I also noticed that my preferred editor was not available in the list, so I added it.
=> Add VS Code as possible editor and open html files in browser.

pyworkflow/apps/pw_schedule_run.py, pyworkflow/gui/project/viewprotocols.py, pyworkflow/project/project.py, pyworkflow/protocol/protocol.py
Visualize schedule.log if exists.
Fix workflow export error: https://github.com/scipion-em/scipion-pyworkflow/issues/158
Export browse window starts at home.
Schedule: fix "wait for" not working. Avoid updating protocols twice in the same loop (when prerequisites existed)
Closes #158
=> Fix "wait for" and visualize schedule.log

pyworkflow/plugin.py, pyworkflow/protocol/bibtex.py, pyworkflow/utils/utils.py
Lazy initialization dictionary class
Used for _bibtex dictionaries.
Removed old bibtex parsing code (0.5)
Dev warining: in case _bibtex present at "package" folder. Now is done deferred upon demand.
=> Do not parse bibtex at module init

pyworkflow/utils/path.py
* Remove the folder related with the specific protocol within the scratch if it exists
- This is a case when a test is launched and it fails or is aborted(the folder stays in the scratch)
=> * Remove the folder related with the specific protocol within the scratch if it exists

pyworkflow/constants.py, pyworkflow/protocol/executor.py
This fixes an issue reported by email, where user was setting several items in the GPUs and several mpis.
````
Traceback (most recent call last):
File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/apps/pw_protocol_mpirun.py", line 54, in <module>
runProtocolMainMPI(projectPath, dbPath, protId, comm)
File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 2229, in runProtocolMainMPI
executor = MPIStepExecutor(hostConfig, protocol.numberOfMpi.get() - 1,
File "/usr/local/apps/scipion/3.0.6/anaconda/envs/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 342, in __init__
ThreadStepExecutor.__init__(self, hostConfig, nMPI, **kwargs)
File …
```
=> Gpu chunk fix

pyworkflow/gui/project/viewprotocols.py, pyworkflow/project/project.py, pyworkflow/protocol/executor.py, pyworkflow/protocol/protocol.py
Steps window:
- Show status.
- Reset status, useful in some cases when a step finishes and you want to run it again (createOutputStep outputting nothing after many hours of run)
Protocol:
_setStatusStep --> renamed to a more generic _updateSteps, receiving a lambda (callback to do the update)
cpuTime (NEW) Integer: incremented on every finished step.
_finalizeStep --> To finish a step anytime is "closed" (finished, aborted, failed)
setRunning (overwritten to keep initTime when RESUMING and therefore have a "better" Wall time.
viewprotocols.py: Tooltip showing CPU time and Wall time
Closes #127
=> Review of protocol time (CPU time and Wall time)

pyworkflow/constants.py, pyworkflow/project/project.py, pyworkflow/project/scripts/fix_links.py, setup.py
Usage: scipion3 run fix_links PROJECT SEARCH_DIR
PROJECT: provide the project name to fix broken links in the imports.
SEARCH_DIR: provide a directory where to look for the files.
and fix the links.
This will fix broken links (in the filesystem) that are pointed by a set produced by an import movies protocol
=> fix_links entry point added

pyworkflow/utils/process.py, pyworkflow/utils/utils.py, requirements.txt
* Allow to set a 'prepend' string in the Environ: It will be used when building the command to execute. This allows to set pre-loading commands that are more complex than just defining environment variables (e.g modules system). For example, one could set in Relion: ```env.setPrepend('module load relion-3.1.1;')```. If not defined, it should not affect and maintain the current behavior.
=> Allow to setup a prepend command in the Environ

pyworkflow/mapper/sqlite.py, pyworkflow/mapper/sqlite_db.py
I have a 4.5 million set of particles, when running the protocol "localrec extract particles2 I get the error Error: database or disk is full
It seems that the executed SQL command is: SELECT * FROM Objects WHERE 1 ORDER BY c09,c03,id ASC ;
This command creates a temporary file several times larger then the database (which is 8.8 Gb), this temporary file is too large for my /tmp directory
So I have modified the mapper such that it uses the local dir as temporary directory.
=====
SQL code that shows that the problem is indeed the temp directory
carmen@clark-cinco:~$ sqlite3 /home/carmen/ScipionUserData/projects/MartaM_Ad5_delta7/Runs/006674_ProtLocalizedRecons/coordinates.sqlite 
SQLite version 3.27.2 2019-02-25 16:06:06
Enter ".help" for usage hints.
sqlite> .output kk      -- rediret …
=> set sqlite temporal directory

requirements.txt
This is needed for a new wizard to react to the version and reduce possibilities.
3.2.2 is still maximum supported version. At some point, we might want to upgrade it to something newer (3.4.x) but it will require some testing, so not doing it now.
=> Ensure 3.6+ python envs have 3.2.2 version of matplotlib. 3.5 will have 3.0.3

pyworkflow/constants.py, pyworkflow/gui/form.py
This is a quick fix to tolerate errors when loading plugins icons.
This goes as a hotfix straight to master.
=> Tolerate errors loading plugin icons

pyworkflow/plugin.py
to get access at the path of a plugin
=> plugin.py: Splited getPluginTemplateDir

CHANGES.txt, pyworkflow/apps/pw_schedule_run.py
Fixing a bug for static protocols. When a protocol had another protocol as input, it failed to wait until it had finish.
=> Fix bug in pw_schedule_run

CHANGES.txt, pyworkflow/apps/pw_run_tests.py, pyworkflow/tests/tests.py, pyworkflow/utils/log.py
This should bring back the output in the tests. 
Progresively, testing code, should replace "prints" with "logger.info" to benefit from the logging functionality.
=> Fix test output

pyworkflow/utils/process.py
Fixes #364 . @pconesa, I think CUDA_VISIBLE_DEVICES is quite common var name to happen inside programname. The syntax is always "CUDA_VISIBLE_DEVICES=0,1" with a comma
But maybe you can offer a better alternative.
I need to test this. At the moment substitution works but I still get all GPU ids in each runJob command - i.e. they are not split among threads..
=> substitute GPU ids in programname

CHANGES.txt, pyworkflow/project/project.py, pyworkflow/protocol/protocol.py
* Fixing an error refreshing the workflow 
- the protocol status changed intermittently
=> * Fixing an error refreshing the workflow

CHANGES.txt, pyworkflow/config.py, pyworkflow/gui/graph_layout.py, pyworkflow/project/project.py
- SCIPION_MAIN_COLOR: If not valid, fallsback to Firebrick
- Project names: Only accepts digits, "letters", - or _. Rest are turned into -
- Show info id debug mode (print) when an infinite loop happens in the protocols graph
=> - Do not allow empty Config variables unless is the default value

pyworkflow/gui/form.py, pyworkflow/gui/project/viewdata.py, pyworkflow/gui/project/viewprotocols.py, pyworkflow/protocol/hosts.py
We do not support remote host executions, so this param wastes form space.
=> remove hostname from the form

CHANGES.txt, pyworkflow/config.py, pyworkflow/constants.py, pyworkflow/gui/form.py, pyworkflow/gui/project/steps.py, pyworkflow/gui/project/utils.py, pyworkflow/gui/project/viewprotocols.py, pyworkflow/object.py, pyworkflow/project/project.py, pyworkflow/utils/utils.py, pyworkflowtests/objects.py, requirements.txt
- Steps window can force finish steps too. Useful for some CS cases.
- "Continue workflow" from improved. Works with more cases. developers:
- Set class has isItemEnabled to be used as callback based on item.isEnabled()
- config.py.OS class (not for GUI): to return distro info (isCentos or isUbuntu) or isWSL (--> new dependency "distro")"...
=> Some tweaks

CHANGES.txt, pyworkflow/project/project.py, pyworkflow/protocol/launch.py
Better case-specific implementation of pID and jobID. 
Three scenarios: 
1. Normal execution (pID). 
2. Sending the entire protocol to the queue (jobID). 
3. Sending individual steps (jobID per step + pID for the protocol).
=> Correct implementation of protocols jobIDs and pIDs

CHANGES.txt, pyworkflow/gui/form.py, pyworkflow/protocol/executor.py, pyworkflow/utils/process.py
* This occurs when a form is used to launch a subworkflow from the protocol.
=> Avoiding a double process when launching a workflow using the protocol form

CHANGES.txt, pyworkflow/project/project.py, pyworkflow/protocol/executor.py, pyworkflow/protocol/protocol.py
When sending the steps to the queue with thread parallelization, an error might occur due to the recursive use of cursors when updating the job IDs, as two steps could try to modify the database simultaneously. To handle this situation, we used a lock mechanism to ensure that only one thread can modify the database at a time, changing the Lock object to Rlock. Recursive locks allows a thread to acquire lock on same object more than one time, thus avoiding deadlock situation. This fixed the concurrency problems we had before.
=> Step Queue executor: fix recursive use of cursors

pyworkflow/gui/project/viewprotocols_extra.py
Pyworkflow version:
```
Name: scipion-pyworkflow
Version: 3.8.0
Summary: Simple workflow platform used in scientific applications, initially developed within the Scipion framework for image processing in Electron Microscopy.
Home-page: https://github.com/scipion-em/scipion-pyworkflow
Author: J.M. De la Rosa Trevin, Roberto Marabini, Grigory Sharov, Josue Gomez Blanco, Pablo Conesa, Yunior Fonseca Reyna
Author-email: delarosatrevin@scilifelab.se, roberto@cnb.csic.es, gsharov@mrc-lmb.cam.ac.uk, josue.gomez-blanco@mcgill.ca, pconesa@cnb.csic.es, fonsecareyna@cnb.csic.es
License: 
Location: /data/relocated/miniconda/envs/scipion3/lib/python3.8/site-packages
Requires: bibtexparser, configparser, distro, importlib-metadata, matplotlib, numpy, pillow, psutil, requests, tkcolorpicker
Required-by: …
```
=> Fix: second argument provided

pyworkflow/utils/path.py
Creating an absolute symlink in the creatAbsLink function. Otherwise, the link may be created relative to the CWD
=> Using absolute path for absolute symlinking

pyworkflow/utils/utils.py
We have a lot of references with keys like: `month = may`. Apparently, such definition is not correct (https://github.com/sciunto-org/python-bibtexparser/issues/222#issuecomment-427621694). 
In Scipion methods tab you will get:
```
ERROR generating methods info: 'may'
Could not load all methods:'may'
```
Instead of replacing `may` with `{may}` in all plugins the fix suggested here sets an extra option to the parser.
=> bibtex parser fix

pyworkflow/plugin.py
Raising a generic `Exception` class eliminates the possibility for anyone using this method of capturing a precise execption type in their code.
As this method aims to handle both `ImportError` and `ModuleNotFound` exceptions, and `ImportError` is parent for `ModuleNotFound`, raising `ImportError` seems like a good enough choice for taking into account both cases at once.
=> Change exception class

pyworkflow/gui/form.py
Without the fix, I get something strange with the threads help and MPI help joined together
With the fix, it looks as it should
=> add missing line break before mpi help

pyworkflow/protocol/protocol.py
Many arguments like --nodes, --cpus-per-tasks, etc cannot have zero value. I added a workaround to avoid this issue by setting the value to at least 1.
=> Prevent 0 values on slurm script arguments
